version: 2.1
orbs:
  docker: circleci/docker@0.1.0
workflows:
  build-and-publish:
    jobs:
      - docker/publish:
          name: build-and-publish-alpine-image-dockerhub
          image: $DOCKER_LOGIN/alpine-ci
          dockerfile: alpine.dockerfile
          context: general
          filters:
            branches:
              only: master
          after_build:
            - run:
                name: Tag as latest
                command: |
                  docker tag \
                    docker.io/$DOCKER_LOGIN/alpine-ci:$CIRCLE_SHA1 \
                    docker.io/$DOCKER_LOGIN/alpine-ci:latest
            - run: docker push docker.io/$DOCKER_LOGIN/alpine-ci:latest
      - docker/publish:
          name: build-and-publish-debian-image-dockerhub
          image: $DOCKER_LOGIN/debian-ci
          dockerfile: debian.dockerfile
          context: general
          filters:
            branches:
              only: master
          after_build:
            - run:
                name: Tag as latest
                command: |
                  docker tag \
                    docker.io/$DOCKER_LOGIN/debian-ci:$CIRCLE_SHA1 \
                    docker.io/$DOCKER_LOGIN/debian-ci:latest
            - run: docker push docker.io/$DOCKER_LOGIN/debian-ci:latest
      - docker/publish:
          name: build-and-publish-arm32v7-image-dockerhub
          image: $DOCKER_LOGIN/arm32v7-ci
          dockerfile: arm32v7.dockerfile
          context: general
          filters:
            branches:
              only: master
          before_build:
            - run:
                name: Download qemu binary
                command: |
                  docker run --rm --privileged multiarch/qemu-user-static:register --reset
                  curl -OL https://github.com/multiarch/qemu-user-static/releases/download/v3.1.0-2/qemu-arm-static
                  chmod +x qemu-arm-static
          after_build:
            - run:
                name: Tag as latest
                command: |
                  docker tag \
                    docker.io/$DOCKER_LOGIN/arm32v7-ci:$CIRCLE_SHA1 \
                    docker.io/$DOCKER_LOGIN/arm32v7-ci:latest
            - run: docker push docker.io/$DOCKER_LOGIN/arm32v7-ci:latest
